### ISSUE TITLE
[Suggestion] disable promoted ads

### ISSUE THREAD

**Issue by tupac55** [lint/TFDidThatSay#1]
Hi, i've installed your Reddit++ I'm liking it so far to be able to see what was deleted comment. But can you also disable promoted ads from the app ?

**Comment by syto203** [comment]
Reddit++ isn’t supported here xD.
As for the ads this isn’t the function of this tweak, I can’t speak for the dev but removing ads isn’t in this tweak’s scope. This tweak only shows deleted/edited comments.

**Comment by tupac55** [comment]
Oups sorry, the link in reddit++ lead me here :D thanks anyway !

**Comment by lint** [comment]
There's a tweak called "Reddit No Ads" by Kemmis which does what you're looking for.
