### ISSUE TITLE
Apollo will crash when using TFDidThatSay? on a post

### ISSUE THREAD

**Issue by gerbil-snot** [lint/TFDidThatSay#2]
It’s works just fine on a comment, but if you do it on the actual post, it crashes. 

Crash Report here:
https://pastebin.com/99pi1Tac

**Comment by lint** [comment]
Just to clarify, on text posts does this happen every time without fail?

**Comment by gerbil-snot** [comment]
Sorry for the really late response

Yes, on text posts, it crashes every time without fail

**Comment by lint** [comment]
@gerbil-snot, with version 1.3.3 of TFDidThatSay ([deb available here](https://github.com/lint/repo/raw/master/debs/com.lint.undelete_1.3.3_iphoneos-arm.deb)) and the latest Apollo update, does it continue to crash?

**Comment by gerbil-snot** [comment]
The latest version (1.3.3) doesn’t even give the option to use TFDidThatSay? on a post. It is working on comments well though

**Comment by lint** [comment]
@gerbil-snot, in the settings, if you have it shoe on all text posts instead of just deleted ones, does the option appear? or still no

**Comment by gerbil-snot** [comment]
It’s starting showing up again, not sure if it fixed itself or you pushed an update, the deleted comments and posts only toggle was already off so that wasn’t the issue. Fixed now though so I guess it doesn’t matter
