### ISSUE TITLE
Currently broken in iOS 13.5

### ISSUE THREAD

**Issue by gerbil-snot** [lint/TFDidThatSay#4]
This tweak fails to appear in Apollo’s long hold menu as seen here:
![FB8E4E12-8797-4E39-98EA-5E6EE06BC32A](https://user-images.githubusercontent.com/29874563/83312901-b7b09680-a1d9-11ea-98a9-cb522baaeac2.png)

The same goes for posts

**Comment by phzeller** [comment]
The tweak works on iOS 13.5 if you downgrade Apollo to Version 1.7.4. Seems like Apollo 1.8 has broken the tweak, unfortunately.

**Comment by lint** [comment]
Yeah, Apollo 1.8 has broken some things unfortunately. I have fixed the action itself, and I am nearing completion in adding the option to the context menu for iOS 13. Should be finished soon.

**Comment by lint** [comment]
1.3.3 adds Apollo 1.8 support and adds the option to the context menu.
