### ISSUE TITLE
Disables Apollo Ultra

### ISSUE THREAD

**Issue by stryderwilk** [lint/TFDidThatSay#5]
Unable to purchase or restore Apollo Ultra subscription.

**Comment by lint** [comment]
Hmm, I don't see how TFDidThatSay would cause that issue. If you uninstall it and try again, does anything change?

**Comment by stryderwilk** [comment]
Turns out it was actually tied to the way the App Store operates with this jailbreak. I ran the command line 

>launchctl reboot userspace

and it fixed it system-wide. Closing this issue, sorry for the mix-up.

**Comment by lint** [comment]
No worries, glad you got it sorted out.
