### ISSUE TITLE
Reddit v2021.13.0 crashing

### ISSUE THREAD

**Issue by JoeyEamigh** [lint/TFDidThatSay#7]
Error code according to Cr4shed - `{"NSExceptionReason":"+[CommentTreeNode updateContentViewsForData:]: unrecognized selector sent to class 0x1081742e8","ProcessBundleID":"com.reddit.Reddit","ProcessName":"Reddit","Culprit":"tfdidthatsay.dylib"}`

iPhone 12 Pro and iOS 14.3

Just wanted to report in case you didn’t know! Thank you!

**Comment by hero3210** [comment]
This crash happens on version 2021.09.0 and later. 

v2021.08.0 and earlier work fine according to my tests.

[a comment to test on](https://reddit.com/r/jailbreak/comments/be949c/_/el43nxe/)

**Comment by booleangit** [comment]
> v2021.08.0 and earlier work fine according to my tests.
> 
Thanks a lot! Now I don't have to try 20+ versions myself 🤗
