### ISSUE TITLE
Apollo beta 1.10.99 (89) crashing

### ISSUE THREAD

**Issue by r03n-d** [lint/TFDidThatSay#9]
Apollo crashes as soon as you press the little eye on a comment. This didn’t happen with the (88) build.

**Comment by IntriguingTiles** [comment]
[I've compiled a build that should fix this.](https://cdn.discordapp.com/attachments/408346940234006559/847622590205263882/com.lint.undelete_1.4.1-1debug_iphoneos-arm.deb)

**Comment by edmechem** [comment]
> I've compiled a build that should fix this.

Nice! Seems to have fixed it. Thx

**Comment by r03n-d** [comment]
> I've compiled a build that should fix this.

It does, thanks!
